### ISSUE TITLE
Add sub surface currents to Buoys

### ISSUE THREAD

**Issue by cgalvarino** [asascience-open/maracoos_assets#3]
- How about a pop-up that just lists them as separate  variables in order from surface to bottom, ignore the fact that it’s a profile?

http://gyre.umeoce.maine.edu/data/gomoos/buoy/archive/PR1/ingest/PR1_currents_10_ingest.txt
http://gyre.umeoce.maine.edu/data/gomoos/buoy/archive/PR2/ingest/PR2_currents_10_ingest.txt
http://gyre.umeoce.maine.edu/data/gomoos/buoy/archive/PR3/ingest/PR3_currents_10_ingest.txt
http://gyre.umeoce.maine.edu/data/gomoos/buoy/archive/VI1/ingest/VI1_currents_10_ingest.txt
http://gyre.umeoce.maine.edu/data/gomoos/buoy/archive/VIA/ingest/VIA_currents_10_ingest.txt

@kknee

**Comment by cgalvarino** [comment]
@kknee I need a lon,lat and a name for each platform and what you want this group listed as in the TOC.  Or do these currents get lumped together w/ their NDBC popup?  If so, what is the NDBC ID for each?

**Comment by cgalvarino** [comment]
After looking at the data, I think we need a separate layer for these.  Mergnig them w/ an NDBC popup would probably be hard to digest.

**Comment by kknee** [comment]
Yes, separate layer, call it caricoos buoys for now.

Sent from my iPhone

On Aug 29, 2015, at 12:05 PM, Charlton Galvarino <notifications@github.com<mailto:notifications@github.com>> wrote:

After looking at the data, I think we need a separate layer for these. Mergnig them w/ an NDBC popup would probably be hard to digest.

—
Reply to this email directly or view it on GitHubhttps://github.com/asascience-open/maracoos_assets/issues/3#issuecomment-136005458.

This e-mail message and any attached file is the property of the sender and is sent in confidence to the addressee only.
Internet communications are not secure and RPS is not responsible for their abuse by third parties, any alteration or corruption in transmission or for any loss or damage caused by a virus or by other means.

Any advice contained in this e-mail is for information purposes only.

RPS Group Plc, company number: 208 7786 (England). Registered office: 20 Western Avenue Milton Park Abingdon Oxfordshire OX14 4SH.
RPS Group Plc web link: http://www.rpsgroup.com

**Comment by cgalvarino** [comment]
Will do.  Don't forget I still need lon,lat for each.

**Comment by cgalvarino** [comment]
I have them in fake positions:
![image](https://cloud.githubusercontent.com/assets/180985/9565337/310abb50-4e97-11e5-8c21-2a55330e252d.png)

Here is a sample "sensor" list w/ a plot below it.
![image](https://cloud.githubusercontent.com/assets/180985/9565338/4cd6ace0-4e97-11e5-993f-663400e44efa.png)

The problem is for platforms w/ a lot of bins.  Can we filter some of these out since this viz approach isn't perfect anyway?  If so, which ones to filter out?
![image](https://cloud.githubusercontent.com/assets/180985/9565341/625e4d16-4e97-11e5-8a2a-8b9ee651167e.png)

**Comment by cgalvarino** [comment]
@kknee bump

**Comment by cgalvarino** [comment]
@kknee Confused.  Was I supposed to delpoy this?

**Comment by kknee** [comment]
@cgalvarino here are names and positions

PR1 - PR108 : CarICOOS Data Buoy A; 17° 51.60´N , 66° 31.43´W 
PR2 - PR206: CariCOOS Data Buoy B; 18° 28.46, 66° 5.94´W 
PR3 - PR303 : CARICOOS Data Buoy E; 18° 15.58´N;  65° 27.44´W 
VI1 - VI105 : CarICOOS Data Buoy C; 18° 15.08´N; 64° 46.01´W 
VIA - VIA03 : USVI EPSCOR Data Buoy A; 18° 15.44´N; 65° 0.24´W 

The scrolling implemented for MARACOOS asset map should negate the need to filter, yes?

Can you update names and positions and deploy?

**Comment by cgalvarino** [comment]
Well, this is unfortunate.  I can't seem to find any of this code.  Somehow it has gotten lost over time, so I get to reinvent the wheel.
